### ISSUE TITLE
GSOC-Task #1: Visualizing 2D and 3D Grid objects

### ISSUE THREAD

**Issue by fverdugo** [gridap/GridapMakie.jl#16]
cc  @paurierap @ericneiva @amartinhuertas 

*This task is to be further defined in the kick-off meeting*

## Intro

Being able to visualize instances of `Gridap.Geometry.Grid` is the cornerstone to visualize other Gridap objects. So, it is a good place to start.

Given a  2D `Grid` object (3D and 1D will be covered in subsequent tasks), we typically want the following kind of visualizations (now they are done with paraview). Here, I am using this code to generate a simple grid of triangles:

```julia
using Gridap
using Gridap.ReferenceFEs
using Gridap.Geometry
using Gridap.Visualization

model = CartesianDiscreteModel((0.,1.5,0.,1.),(15,10)) |> simplexify
grid = get_grid(model)
celldata = rand(num_cells(grid))
nodaldata = rand(num_nodes(grid))
write_vtk_file(grid,"grid",celldata=["d1"=>celldata],nodaldata=["d2"=>nodaldata])
```

![fig1](https://user-images.githubusercontent.com/48508177/119154277-4b661d00-ba52-11eb-887b-7722932c9e6c.png)  |  ![fig2](https://user-images.githubusercontent.com/48508177/119154321-5620b200-ba52-11eb-8a31-1665c5edb08f.png) |  ![fig3](https://user-images.githubusercontent.com/48508177/119154375-63d63780-ba52-11eb-9007-82bb9db8bd54.png)
--- | --- | --- 
surface  | surface and edges | prescribe edge width 
![fig4](https://user-images.githubusercontent.com/48508177/119154839-d6dfae00-ba52-11eb-9c1c-604fa2ff974b.png) |  ![fig7](https://user-images.githubusercontent.com/48508177/119154860-de06bc00-ba52-11eb-8199-dcd8e955a882.png) | ![fig5](https://user-images.githubusercontent.com/48508177/119154884-e3640680-ba52-11eb-9a4b-8d3d565b8e3c.png)
set surface and edge color | set surface color via a cell field  | set surface color via a nodal field
![fig6](https://user-images.githubusercontent.com/48508177/119155295-4f466f00-ba53-11eb-9b81-d8064199c1f4.png) | ![fig8](https://user-images.githubusercontent.com/48508177/119155330-58374080-ba53-11eb-814f-4d72d2225eda.png)
display colorbar | change colormap

## TODO (outdated, see below for the updated steps)

-  Familiarize with Makie.jl and find out which are the low level plotting command needed to reproduce these images
-  Propose a user API to generate these figures in a convenient way
-  Implement the API (possibly by reusing code in the `src` folder)
-  Extend to quads

## Notes

Most of the functionality we need is provided by the Makie function [`mesh`](https://makie.juliaplots.org/stable/plotting_functions/mesh.html#mesh), but it is likely that this does not cover all cases.

**Comment by fverdugo** [comment]
Steps:

- [ ] create a new branch `gsoc2021-master` (consensus branch, all test should pass)
- [ ] Create you own work branch e.g. `pr-task1` (you are free to use this branch as you want)
- [ ]  Clear code in `GridapMakie` module
- [ ] Add `Gridap="0.16"` in `Project.toml`  `[compat]` section. You perhaps need to resolve your environment at this point. `pkg> resolve`.
- [ ]  Implement conversion `Griadp.Grid` -> `GeometryBasics.Mesh` and implement
```julia
function AbstractPlotting.convert_arguments(pt::PlotType, grid::Grid)
  convert_arguments(pt,UnstructuredGrid(grid))
end
function AbstractPlotting.convert_arguments(::PlotType, grid::UnstructuredGrid)  
  xs = get_node_coordinates(grid)
  Tp = eltype(eltype(xs))
  D = length(eltype(xs))
  ps = collect(reinterpret(GeometryBasics.Point{D,Tp},xs))
  cns = get_cell_node_ids(grid)
  Tf = eltype(eltype(cns))
  fs = collect(lazy_map(GeometryBasics.NgonFace{D+1,Tf},cns))
  m = GeometryBasics.Mesh(GeometryBasics.connect(ps,fs))
  m
end
```
- [ ] Try to reproduce the plots above using `Makie` functions like `mesh` and `wireframe`.  Add this code into a test.
- [ ] Move from Travis to GH actions to run the tests.
- [ ]  Explore the extension to quadrilateral elements (i.e., remove `simplexify`).

**Comment by amartinhuertas** [comment]
Some relevant links/info interchanged during 07/06/21 meeting:

> Eric Neiva17:41
      - run: sudo apt-get update && sudo apt-get install -y xorg-dev mesa-utils xvfb libgl1 freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev
      - run: DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' julia --project=@. -e 'using Pkg; Pkg.test(coverage=true)'
Eric Neiva17:43
https://github.com/JuliaPlots/GLMakie.jl/blob/master/.github/workflows/ci.yml
https://github.com/JuliaPlots/GLMakie.jl/blob/3762f689ec785ff40b429c9ecca7d81a54895ed0/.github/workflows/ci.yml#L41
Eric Neiva17:45
https://github.com/JuliaPlots/GLMakie.jl#troubleshooting-opengl

**Comment by fverdugo** [comment]
@paurierap perhaps it is better to use `convert_single_argument` instead of `convert_arguments`.

**Comment by fverdugo** [comment]
- [ ] gitignore .DS_STORE files
- [ ] import AbstractPlotting instead of Makie
- [ ]  Try to define conversion for all plot types at once (if possible)

**Comment by paurierap** [comment]
Before the meeting on 21/06/2021, the conversions implemented from `Gridap` types to `Makie` types allow us to plot: 

![fig1](https://user-images.githubusercontent.com/64323465/122685303-c7e34b80-d20a-11eb-9bb5-0fde7b7ece07.png)  |  ![fig2](https://user-images.githubusercontent.com/64323465/122685309-cca7ff80-d20a-11eb-960a-a3484d4e01b2.png) |  ![fig3](https://user-images.githubusercontent.com/64323465/122685300-c580f180-d20a-11eb-925f-20c17ab16329.png)
--- | --- | --- 
2D surface + set color (extended to quads too) | 2D  edges + set color and linewidth (only for simplices)| 2D surface color via a nodal field + choice of colormap (and colorbar) 
![fig4](https://user-images.githubusercontent.com/64323465/122685308-cb76d280-d20a-11eb-83ca-401bf33acf65.png)  |  ![fig5](https://user-images.githubusercontent.com/64323465/122685313-cdd92c80-d20a-11eb-9a98-013c6b58ad9c.png) |  ![fig6](https://user-images.githubusercontent.com/64323465/122685306-ca45a580-d20a-11eb-88dd-0b41d6b104f0.png)
3D surface + set color (extended to quads too) | 3D  edges + set color and linewidth (only for simplices)| 3D surface color via a nodal field + choice of colormap (and colorbar) 

So far, we still need to address the drawing of quadrilateral edges in either dimension as well as the plotting of a cell field.

**Comment by fverdugo** [comment]
Code discussed in meeting 2021-06-21 for visualizing 3D meshes. (i.e., convert volume mesh to boundary mesh of triangles)
```julia
using Gridap
using Gridap.Geometry
using Gridap.Visualization


domain = (0,1,0,1,0,1)
cells = (2,2,2)
grid = CartesianGrid(domain,cells)

write_vtk_file(grid,"grid")

topo = GridTopology(grid)

labels = FaceLabeling(topo)

model = DiscreteModel(grid,topo,labels)

face_grid = Grid(ReferenceFE{2},model)


face_to_mask = get_face_mask(labels,"boundary",2)

@show num_cells(face_grid)
@show length(face_to_mask)

write_vtk_file(face_grid,"face_grid",celldata=["mask"=>collect(Int,face_to_mask)])

boundary_grid = GridPortion(face_grid,face_to_mask) |> simplexify

write_vtk_file(boundary_grid,"boundary_grid")

```

**Comment by fverdugo** [comment]
TODO steps

- [ ] CI integration i.e., copy file https://github.com/gridap/GridapPETSc.jl/blob/master/.github/workflows/ci.yml More info here: https://docs.github.com/en/actions/guides/about-continuous-integration
- [ ] For 3D conversions, use a boundary triangulation of triangles, see code above.
- [ ] Open a PR against `gsoc2021-master` branch

**Comment by fverdugo** [comment]
closed via #18
